# Use python:3.13-slim as a base image 


# Set /Day8 as a working directory in the container


# Copy everything in the working directory to /Day8 in the container


# Install packages and libraries


# expose port 8000


# run the ex01.py as fastapi server.
